name: auto_hide_keyboard
description: A Flutter package that automatically hides the soft keyboard when the user taps outside of text input fields or scrolls the page.
homepage: https://github.com/idootop/auto_hide_keyboard

version: 1.1.1

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  visibility_detector: ^0.4.0+2

dev_dependencies:
  lints: ^6.0.0
