name: auto_hide_keyboard
description: Automatically hides the keyboard when tapping outside the TextField.

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.4.0+2

dev_dependencies:
  lints: ^2.0.0
