name: auto_hide_keyboard
description: An example of automatically retracting the soft keyboard in Flutter by clicking on a blank space.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.11.0
  visibility_detector: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
